# volumes:
volumes:
  fastapi-data:
    external: true
  mongo-data:
    external: true
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: meme_reactor
      MONGO_INITDB_ROOT_PASSWORD: memereactor

  fastapi:
    environment:
      CORS_HOST: ${REACT_APP_GHI_HOST}
      SIGNING_KEY: ${SIGNING_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 8000
      DATABASE_URL: ${DATABASE_URL}
      DB_NAME: ${DB_NAME}
      IMGFLIP_USERNAME: ${IMGFLIP_USERNAME}
      IMGFLIP_PASSWORD: ${IMGFLIP_PASSWORD}
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${REACT_APP_GHI_HOST}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: meme_reactor
      ME_CONFIG_MONGODB_ADMINPASSWORD: memereactor
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      - mongo
