# volumes:
volumes:
  fastapi-data:
    external: true
  pg-admin:
    external: true
services:
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: randallcrandon@gmail.com
      PGADMIN_DEFAULT_PASSWORD: BR0NT0SAURUS
      PGADMIN_DISABLE_POSTFIX: 1

  fastapi:
    environment:
      CORS_HOST: ${REACT_APP_GHI_HOST}
      SIGNING_KEY: ${SIGNING_KEY}
      SUPERMEMES_API_KEY: ${SUPERMEMES_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGO_URI: mongodb://root:example@mongo:27017/
      WAIT_HOSTS: db:5432
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${REACT_APP_GHI_HOST}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
